export default [

    {
        id: 1,
        name: "Rose",
        botanical_name: "Rosa rubiginosa",
        family: "Rosaceae",
        family_common: "Rosier",
        color: "Red, Pink, White",
        informations: "Roses are the queens of the flower world, popular for their classic beauty and romantic symbolism. They come in a rainbow of colours, with each colour telling a different story of love, friendship, or respect. They are also associated with people born in June. Roses are known for their layered petals and rich fragrance, which has made them a favourite in perfumery for centuries. Whether in a lavish bouquet or a single stem, roses capture hearts everywhere.",
        height_cm: 50,
        pictureUrl: "https://i.pinimg.com/1200x/67/00/0d/67000d8a071fc7df0be777b581db45e0.jpg",
    },
    {
        id: 2,
        name: "Tulip",
        botanical_name: "Tulipa spp. or T. gesnerana",
        family: "Liliaceae",
        family_common: "Lily family",
        color: "Orange, Pink, Purple, Red, White, Yellow",
        informations: "Tulips are springtime stars with their clean, elegant shape and a cheerful palette of colours. These bulbs are some of the earliest to bloom in spring, making them a symbol of rebirth and new beginnings. Tulips are native to Central Asia, but gained popularity in the Netherlands in the 17th century, sparking Tulip Mania during which bulbs were incredibly valuable. Tulips are perfect for gardens, pots, and as cut flowers in stunning floral arrangements.",
        height_cm: 45,
        pictureUrl: "https://i.pinimg.com/1200x/58/e7/4f/58e74f21b89d91ff2ca05666b0545d56.jpg",
    },
    {
        id: 3,
        name: "Carnation",
        botanical_name: "Dianthus caryophyllus",
        family: "Caryophyllaceae",
        family_common: "Pink family",
        color: "Pink, Red, White, Yellow, Purple",
        informations: "Carnations are beloved for their ruffled appearance and clove-like scent. With a history dating back over 2,000 years, they symbolize love, fascination, and distinction. Carnations are January's birth flower and are commonly associated with Mother's Day in many countries. These hardy flowers are long-lasting as cut flowers, making them popular in bouquets and corsages. Each color carries its own meaning, from pure love (red) to gratitude (pink) to remembrance (white).",
        height_cm: 45,
        pictureUrl: "https://i.pinimg.com/1200x/1e/f9/0f/1ef90f34418ed3ba53e6b67c41c0df2d.jpg",
    },
    {
        id: 4,
        name: "Peony",
        botanical_name: "Paeonia lactiflora",
        family: "Paeoniaceae",
        family_common: "Peony family",
        color: "Pink, Red, White, Yellow, Coral",
        informations: "Peonies are luxurious blooms known for their large, full flowers and intoxicating fragrance. With roots in Chinese tradition where they symbolize wealth and honor, peonies are now beloved worldwide for their showy appearance. These perennials can live for over 100 years, making them a symbol of longevity and prosperity. Peonies bloom briefly in late spring to early summer, adding to their special appeal. They're popular in wedding bouquets, representing good fortune and a happy marriage.",
        height_cm: 70,
        pictureUrl: "https://i.pinimg.com/1200x/82/e1/86/82e18658714bd11b8f6b93407a85104d.jpg",
    },
    {
        id: 5,
        name: "Sunflower",
        botanical_name: "Helianthus annuus",
        family: "Asteraceae",
        family_common: "Daisy family",
        color: "Yellow, Orange, Red, Brown",
        informations: "Sunflowers are iconic for their tall stalks and bright, sun-like blooms that track the sun's movement across the sky. Native to North America, these cheerful flowers symbolize adoration, loyalty, and longevity. Beyond their beauty, sunflowers are valuable crops for their seeds and oil. Their distinctive appearance has inspired artists throughout history, most famously Vincent van Gogh. With their radiant appearance and positive symbolism, sunflowers bring warmth and joy to gardens and floral arrangements alike.",
        height_cm: 150,
        pictureUrl: "https://i.pinimg.com/1200x/a6/66/8c/a6668c75ccd866c1954de1faa92acd6c.jpg",
    },
    {
        id: 6,
        name: "Orchid",
        botanical_name: "Orchidaceae (family)",
        family: "Orchidaceae",
        family_common: "Orchid family",
        color: "Purple, White, Pink, Yellow, Blue, Green",
        informations: "Orchids are exotic and elegant flowers, representing one of the largest flowering plant families with over 25,000 species. These sophisticated blooms symbolize luxury, beauty, and strength. Orchids grow on every continent except Antarctica and have adapted to diverse environments from rainforests to deserts. Their complex structure and vibrant colors have made them prized by collectors for centuries. As houseplants, they're valued for their long-lasting blooms and relatively low maintenance when properly understood.",
        height_cm: 40,
        pictureUrl: "https://i.pinimg.com/1200x/10/a5/ba/10a5ba3c2d9705f2f372827daa1c812f.jpg",
    },
    {
        id: 7,
        name: "Lily",
        botanical_name: "Lilium spp.",
        family: "Liliaceae",
        family_common: "Lily family",
        color: "White, Yellow, Pink, Red, Orange",
        informations: "Lilies are elegant, trumpet-shaped flowers known for their strong fragrance and striking appearance. With a history spanning thousands of years across cultures, they symbolize purity, rebirth, and passion. They're the birth flower for May and the 30th wedding anniversary flower. While beautiful, lilies can be toxic to cats and some varieties to dogs. From the majestic Easter lily to the vibrant tiger lily, these blooms make a bold statement in gardens and floral arrangements with their tall stems and distinctive petals.",
        height_cm: 60,
        pictureUrl: "https://i.pinimg.com/1200x/12/ee/65/12ee65685c7deed807b3c4198327ceba.jpg",
    },
    {
        id: 8,
        name: "Alstroemeria",
        botanical_name: "Alstroemeria spp.",
        family: "Alstroemeriaceae",
        family_common: "Peruvian lily family",
        color: "Pink, Purple, Red, Orange, Yellow, White",
        informations: "Alstroemeria, also known as Peruvian lilies or lily of the Incas, are beloved for their spotted, striped petals and impressive vase life of up to two weeks. Native to South America, these flowers symbolize friendship, devotion, and mutual support. Each bloom features six petals with unique markings, resembling small lilies. Alstroemeria have become increasingly popular in floral arrangements due to their durability and wide range of colors. They're relatively easy to grow in temperate climates and make excellent cut flowers for any occasion.",
        height_cm: 58,
        pictureUrl: "https://i.pinimg.com/1200x/02/ea/4a/02ea4aaca4e655947faa4f5103badb85.jpg",
    },
    {
        id: 9,
        name: "Stock",
        botanical_name: "Matthiola incana",
        family: "Brassicaceae",
        family_common: "Mustard family",
        color: "Purple, Pink, White, Red, Yellow",
        informations: "Stock flowers, also known as gillyflowers, are cherished for their spicy, clove-like fragrance and clustered blooms on tall spikes. These old-fashioned favorites symbolize lasting beauty and a happy life. Dating back to Greek and Roman times, stocks have been garden staples for centuries. They come in both single and double-flowered varieties, with the doubles being particularly fragrant. Stocks are cool-season bloomers, making them perfect for spring and fall gardens, and they make excellent cut flowers that fill entire rooms with their sweet scent.",
        height_cm: 72,
        pictureUrl: "https://i.pinimg.com/1200x/21/1a/db/211adb84a92a657c84f52b1d802990cd.jpg",
    },
    {
        id: 10,
        name: "Daffodil",
        botanical_name: "Narcissus spp.",
        family: "Amaryllidaceae",
        family_common: "Amaryllis family",
        color: "Yellow, White, Orange, Pink",
        informations: "Daffodils, with their cheerful trumpet-shaped blooms, are among the first flowers to announce spring's arrival. Also known as narcissus, these bulbs symbolize rebirth, new beginnings, and good fortune. They're March's birth flower and the 10th wedding anniversary flower. Legend has it that the flower was named after a Greek youth, Narcissus, who fell in love with his own reflection. Daffodils naturalize easily, creating stunning drifts of color that return year after year. Their bright yellow is the classic color, but varieties come in white, orange, and even pink combinations.",
        height_cm: 40,
        pictureUrl: "https://i.pinimg.com/1200x/cc/89/60/cc8960e06570dc65a344377c8fda74a4.jpg",
    },
    {
        id: 11,
        name: "Daisy",
        botanical_name: "Bellis perennis",
        family: "Asteraceae",
        family_common: "Daisy family",
        color: "White, Yellow, Pink, Red",
        informations: "Daisies are simple yet charming flowers with their classic white petals surrounding a yellow center. They symbolize innocence, purity, and loyal love, and are April's birth flower. The name comes from 'day's eye' as the flowers open at dawn. Daisies are actually composite flowers—what looks like one flower is actually hundreds of tiny florets. Found on every continent except Antarctica, these resilient blooms have inspired the phrase 'fresh as a daisy.' Their cheerful appearance makes them popular in garden borders, meadows, and casual bouquets.",
        height_cm: 30,
        pictureUrl: "https://i.pinimg.com/1200x/6e/47/d6/6e47d691fe0ae45f831edfd37590f2f1.jpg",
    },
    {
        id: 12,
        name: "Hyacinth",
        botanical_name: "Hyacinthus orientalis",
        family: "Asparagaceae",
        family_common: "Asparagus family",
        color: "Blue, Purple, Pink, White, Yellow",
        informations: "Hyacinths are spring-blooming bulbs known for their intensely fragrant clusters of star-shaped flowers. Named after a figure in Greek mythology, these flowers symbolize sincerity, constancy, and playfulness. They're among the most fragrant spring bulbs, with a sweet perfume that can fill an entire garden. Hyacinths come in a rainbow of colors, each with its own meaning, from blue (constancy) to purple (sorrow) to pink (play). These low-maintenance perennials are perfect for borders, containers, and forcing indoors during winter for early spring color.",
        height_cm: 71,
        pictureUrl: "https://i.pinimg.com/1200x/f1/66/67/f16667534fc8228b126221c45556b37e.jpg",
    },
    {
        id: 13,
        name: "Iris",
        botanical_name: "Iris spp.",
        family: "Iridaceae",
        family_common: "Iris family",
        color: "Blue, Purple, Yellow, White, Pink, Orange, Brown",
        informations: "Irises are distinctive flowers named after the Greek goddess of the rainbow, reflecting their wide color range. With their unique three-part blooms—three upright petals (standards) and three drooping petals (falls)—they symbolize faith, wisdom, and courage. Irises are February's birth flower and the 25th wedding anniversary flower. From the tall bearded varieties to the delicate Japanese water iris, these versatile perennials thrive in various conditions. Their sword-like foliage adds structural interest even when not in bloom, making them valuable garden additions year-round.",
        height_cm: 66,
        pictureUrl: "https://i.pinimg.com/1200x/12/59/bb/1259bb47cd982c6f5958d4ce6bfbe894.jpg",
    },
    {
        id: 14,
        name: "Chrysanthemum",
        botanical_name: "Chrysanthemum morifolium",
        family: "Asteraceae",
        family_common: "Daisy family",
        color: "White, Yellow, Red, Purple, Pink",
        informations: "Chrysanthemums, often called 'mums,' are fall garden stars with their showy, long-lasting blooms. Cultivated in China for over 2,500 years, they symbolize longevity, joy, and optimism. They're November's birth flower and the 13th wedding anniversary flower. Chrysanthemums come in a stunning variety of forms, from daisy-like singles to pompoms and spiders with spoon-shaped petals. Beyond their ornamental value, chrysanthemum tea is popular in Asian cultures for its medicinal properties. These hardy perennials add vibrant color to gardens when most other flowers have faded.",
        height_cm: 55,
        pictureUrl: "https://i.pinimg.com/1200x/8e/35/1b/8e351b2eb9c48565540a382b99267c3c.jpg",
    },
    {
        id: 15,
        name: "Geranium",
        botanical_name: "Pelargonium spp.",
        family: "Geraniaceae",
        family_common: "Geranium family",
        color: "Red, Pink, White, Purple, Orange",
        informations: "Geraniums are beloved garden classics with their rounded, sometimes scented leaves and clusters of five-petaled flowers. What most people call geraniums are actually pelargoniums, while true geraniums are the hardy perennials known as cranesbills. These cheerful flowers symbolize comfort, good health, and friendship. Geraniums are versatile plants that thrive in containers, hanging baskets, and garden beds. Their variety is impressive—from the common zonal geraniums to ivy geraniums, scented geraniums with fragrances from rose to citrus, and the elegant Martha Washington types with their showy blooms.",
        height_cm: 66,
        pictureUrl: "https://i.pinimg.com/1200x/dc/db/24/dcdb24e47efb489a1232b97efd7fa015.jpg",
    },
    {
        id: 16,
        name: "Magnolia",
        botanical_name: "Magnolia spp.",
        family: "Magnoliaceae",
        family_common: "Magnolia family",
        color: "White, Pink, Purple, Yellow",
        informations: "Magnolias are ancient trees and shrubs featuring large, fragrant flowers that bloom dramatically on bare branches in early spring. Dating back over 100 million years, they're among the oldest flowering plants on Earth and symbolize dignity, perseverance, and love of nature. Their primitive structure, with petal-like tepals arranged in a spiral, reflects their evolutionary age. Southern magnolias with their glossy evergreen leaves and fragrant white blooms are iconic in the American South, while deciduous varieties like star and saucer magnolias herald spring in cooler regions with their spectacular floral displays.",
        height_cm: 43,
        pictureUrl: "https://i.pinimg.com/1200x/87/6f/3d/876f3d482c69cd71018e98756e6a0284.jpg",
    },
    {
        id: 17,
        name: "Lavender",
        botanical_name: "Lavandula spp.",
        family: "Lamiaceae",
        family_common: "Mint family",
        color: "Purple, Blue, Pink, White",
        informations: "Lavender is beloved for its aromatic silver-green foliage and spikes of purple-blue flowers. This Mediterranean native symbolizes purity, silence, and devotion. Its name comes from the Latin 'lavare,' meaning 'to wash,' reflecting its historical use in baths. Beyond its ornamental value, lavender is prized for its essential oil used in perfumes, soaps, and aromatherapy to promote relaxation and sleep. The dried flowers retain their fragrance for months, making them popular for sachets and potpourri. Hardy and drought-tolerant once established, lavender thrives in sunny locations with well-drained soil.",
        height_cm: 60,
        pictureUrl: "https://i.pinimg.com/1200x/3b/25/a2/3b25a231ab6ecd6ddee65ad7a15cc43a.jpg",
    },
    {
        id: 18,
        name: "Poppy",
        botanical_name: "Papaver spp.",
        family: "Papaveraceae",
        family_common: "Poppy family",
        color: "Red, Orange, Yellow, Pink, Purple, White",
        informations: "Poppies are distinctive flowers known for their crepe-paper-like petals and seed pods. The red poppy symbolizes remembrance for soldiers fallen in war, inspired by the poppies that bloomed on battlefields after World War I. Oriental poppies dazzle with their large, bowl-shaped blooms, while Iceland and California poppies add delicate color to meadows and gardens. Poppies are August's birth flower and represent imagination, peace, and eternal sleep in various cultures. Their seeds are culinary staples, used in baking and for poppy seed oil, while some species produce opium, used medicinally but also source of dangerous narcotics.",
        height_cm: 79,
        pictureUrl: "https://i.pinimg.com/1200x/8f/74/2e/8f742e2226ea352ae6a5f21cdf4d0cf6.jpg",
    },
    {
        id: 19,
        name: "Bluebell",
        botanical_name: "Hyacinthoides non-scripta",
        family: "Asparagaceae",
        family_common: "Asparagus family",
        color: "Blue, Purple, Pink, White",
        informations: "Bluebells are enchanting woodland flowers that create magical carpets of nodding, bell-shaped blooms in spring. Native to Western Europe, particularly abundant in the British Isles, they symbolize humility, gratitude, and everlasting love. In folklore, these flowers are believed to call fairies when rung, earning them the nickname 'fairy flowers.' The intense blue hue of traditional English bluebells comes from a unique combination of pigments. Protected in the UK due to declining populations, bluebells face threats from habitat loss and hybridization with the introduced Spanish bluebell. Their sweet scent adds to their charm in forest settings.",
        height_cm: 75,
        pictureUrl: "https://i.pinimg.com/1200x/b2/03/1f/b2031f88da9491d6a9690d662388dcd3.jpg",
    },
    {
        id: 20,
        name: "Marigold",
        botanical_name: "Tagetes spp.",
        family: "Asteraceae",
        family_common: "Daisy family",
        color: "Yellow, Orange, Red",
        informations: "Marigolds are bright, cheerful flowers known for their distinctive ruffled blooms and pungent scent. These easy-to-grow annuals symbolize passion and creativity. In Mexican culture, they're called 'flowers of the dead' (flor de muerto) and play a central role in Day of the Dead celebrations, believed to guide spirits with their vibrant color and strong fragrance. Beyond their ornamental value, marigolds serve practical purposes in gardens by repelling certain pests with their scent. From the tall African marigolds to the compact French varieties, these resilient flowers provide reliable color from summer until frost.",
        height_cm: 35,
        pictureUrl: "https://i.pinimg.com/1200x/b5/ce/7b/b5ce7b5afdac8cbd0e5435d2f169bfeb.jpg",
    },
    {
        id: 21,
        name: "Amaryllis",
        botanical_name: "Hippeastrum spp.",
        family: "Amaryllidaceae",
        family_common: "Amaryllis family",
        color: "Red, Pink, White, Orange, Salmon",
        informations: "Amaryllis are stunning bulbs that produce large, lily-like blooms on tall, hollow stems. What we commonly call amaryllis are actually Hippeastrum species, while true Amaryllis belladonna is known as naked ladies or belladonna lily. These impressive flowers symbolize pride, determination, and radiant beauty. Popular as winter-blooming houseplants and holiday gifts, amaryllis bulbs can produce flowers for years with proper care. Each bulb typically produces 2-3 stems with 4-6 flowers each, creating a dramatic display. Their relatively easy care and reliable blooming make them favorites for both experienced and novice gardeners.",
        height_cm: 73,
        pictureUrl: "https://i.pinimg.com/1200x/e2/83/e7/e283e70f0b2532812193101a8ef9d179.jpg",
    },
    {
        id: 22,
        name: "Camellia",
        botanical_name: "Camellia japonica",
        family: "Theaceae",
        family_common: "Tea family",
        color: "White, Pink, Red, Yellow",
        informations: "Camellias are elegant evergreen shrubs that produce exquisite rose-like blooms during winter and early spring when few other plants flower. Native to eastern Asia, they symbolize admiration, perfection, and longevity. Camellia japonica provides ornamental blooms, while Camellia sinensis gives us tea leaves. Their glossy, dark green foliage makes them attractive year-round landscape plants in mild climates. Camellia blooms can be single, semi-double, or fully double, with forms ranging from simple to peony-like or formal double with perfectly arranged petals. These long-lived shrubs often become cherished garden heirlooms, blooming for generations.",
        height_cm: 32,
        pictureUrl: "https://i.pinimg.com/1200x/63/52/e2/6352e21e22b862b54ee190ed1773d19f.jpg",
    },
    {
        id: 23,
        name: "Begonia",
        botanical_name: "Begonia spp.",
        family: "Begoniaceae",
        family_common: "Begonia family",
        color: "Red, Pink, White, Orange, Yellow",
        informations: "Begonias are versatile ornamental plants prized for their continuous blooms and often striking foliage. With over 1,800 species, they symbolize caution or being cautious in relationships. Begonias come in three main types: fibrous-rooted (wax begonias) for bedding, rhizomatous primarily grown for their spectacular leaves, and tuberous begonias with their large, rose-like flowers. Angel wing begonias, with their spotted, wing-shaped leaves and cascading flower clusters, are popular houseplants. Whether grown for flowers, foliage, or both, begonias offer tremendous variety for containers, hanging baskets, and garden beds in partial shade.",
        height_cm: 48,
        pictureUrl: "https://i.pinimg.com/1200x/17/fd/a6/17fda6101145a2250154195469da49ff.jpg",
    },
    {
        id: 24,
        name: "Dahlia",
        botanical_name: "Dahlia spp.",
        family: "Asteraceae",
        family_common: "Daisy family",
        color: "Red, Orange, Yellow, Pink, Purple, White",
        informations: "Dahlias are show-stopping flowers known for their geometric perfection and incredible diversity. Native to Mexico, where they were grown for food and medicine by the Aztecs, they now symbolize elegance, inner strength, and creativity. Dahlias range from tiny pom-poms to dinner-plate sized blooms, with forms classified into distinct groups like cactus, decorative, and ball types. The national flower of Mexico, dahlias bloom from midsummer until frost, providing vibrant color when many other flowers fade. Their tubers are lifted and stored over winter in cold climates, making them both perennial treasures and annual projects for dedicated gardeners.",
        height_cm: 44,
        pictureUrl: "https://i.pinimg.com/1200x/b3/b2/e0/b3b2e0f92508c0e6f7bbd98db4e9b08c.jpg",
    },
    {
        id: 25,
        name: "Snapdragon",
        botanical_name: "Antirrhinum majus",
        family: "Plantaginaceae",
        family_common: "Plantain family",
        color: "Red, Orange, Yellow, Pink, Purple, White",
        informations: "Snapdragons are whimsical flowers named for their dragon-mouth-shaped blooms that can be 'snapped' open by squeezing the sides. These cool-season favorites symbolize grace, strength, and deception. Children delight in making the flowers 'talk' by pressing the sides to open and close the 'jaws.' Available in dwarf varieties just 6 inches tall to stately types reaching 3 feet, snapdragons offer height and vertical interest in gardens. They're particularly valuable for spring and fall blooms when temperatures are cool. The flowers grow on tall spikes, opening from bottom to top, providing long-lasting color in borders and excellent cut flowers for arrangements.",
        height_cm: 64,
        pictureUrl: "https://i.pinimg.com/1200x/a1/14/78/a114789bceacfd2ebeeacce1d1233236.jpg",
    },
    {
        id: 26,
        name: "Petunia",
        botanical_name: "Petunia x hybrida",
        family: "Solanaceae",
        family_common: "Nightshade family",
        color: "Purple, Pink, Red, Blue, Yellow, White",
        informations: "Petunias are popular summer annuals known for their trumpet-shaped flowers and long blooming season. Related to tobacco and tomatoes, these South American natives symbolize anger and resentment in the language of flowers, despite their cheerful appearance. Modern breeding has produced an astonishing variety—from compact mounds to trailing varieties cascading several feet, from simple single blooms to frilly doubles, and from solid colors to striped, veined, or picotee patterns. Wave petunias revolutionized landscapes with their groundcover-like spread, while more recent innovations include improved weather resistance and self-cleaning habits, eliminating the need for deadheading to keep plants blooming continuously.",
        height_cm: 47,
        pictureUrl: "https://i.pinimg.com/1200x/54/a7/3b/54a73b3ff04162375801e1d1cc8b0b4d.jpg",
    },
    {
        id: 27,
        name: "Pansy",
        botanical_name: "Viola x wittrockiana",
        family: "Violaceae",
        family_common: "Violet family",
        color: "Purple, Blue, Yellow, Red, Orange, White",
        informations: "Pansies are beloved cool-season flowers known for their 'faces'—distinctive markings on flat, rounded petals that resemble cheerful expressions. Developed from wild violas in the early 19th century, they symbolize loving thoughts and remembrance. Their name comes from the French word 'pensée,' meaning 'thought.' Pansies thrive in cool temperatures, making them ideal for spring and fall gardens in most climates, and winter gardens in milder regions. Available in single colors, bicolors, and tricolors, often with contrasting 'whiskers' or dark centers, these cheerful blooms brighten containers, borders, and window boxes when many other plants aren't flowering.",
        height_cm: 32,
        pictureUrl: "https://i.pinimg.com/1200x/4d/c7/48/4dc748a0a3302aab8602c9e6b3018728.jpg",
    },
    {
        id: 28,
        name: "Jasmine",
        botanical_name: "Jasminum spp.",
        family: "Oleaceae",
        family_common: "Olive family",
        color: "White, Yellow, Pink",
        informations: "Jasmine is renowned for its intensely fragrant, star-shaped flowers that perfume the air, especially in the evening. Native to tropical regions, jasmine symbolizes love, beauty, and sensuality across many cultures. It's the national flower of Pakistan and Indonesia and plays important roles in religious ceremonies and perfumery worldwide. While most jasmines are vining plants, some form shrubs, and they can be evergreen or deciduous depending on the species and climate. Common jasmine (Jasminum officinale) offers classic white blooms, while winter jasmine (J. nudiflorum) brings yellow flowers on bare stems during the coldest months, providing welcome color and fragrance.",
        height_cm: 43,
        pictureUrl: "https://i.pinimg.com/1200x/b3/97/85/b39785c38dbaea3376172634f194886b.jpg",
    }
];